### ISSUE TITLE
not working since upgrade to WordPerfect 4.2-en

### ISSUE THREAD

**Issue by Lark-Bookwyrm** [pippinsplugins/Comments-Not-Replied-To#25]
Yesterday, I upgraded to WordPerfect 4.2-en on my wordpress.org blog. Now when I go to the Missing Replies page, my replies show up, as do all comments I have replied to, whether before or since the upgrade. I think the counter is still working; I replied to one comment this morning, and the "missing replies" number went from 44 to 43. Still, I need to easily see which comments I've replied to and which I haven't, and that part seems to be broken.

**Comment by pippinsplugins** [comment]
I just tested this and it's still working fine for me. Closing as invalid.
